### ISSUE TITLE
use BiocManager to install; also example assumes folder existence

### ISSUE THREAD

**Issue by vjcitn** [gevaertlab/AMARETTO#3]
The AMARETTO.R at https://github.com/gevaertlab/AMARETTO/tree/master/RUNNING_AMARETTO_EXAMPLE

uses devtools::install_github

The BiocManager package can be installed from CRAN.  It will resolve dependencies
as well as install_github -- BiocManager::install("gevaertlab/AMARETTO")

Also the example has an early setwd("AMARETTO") but that folder may not be present.

**Comment by ogevaert** [comment]
@vjcitn we are working on the bioconductor submission, and will definitely fix this as well !

**Comment by jayendrashinde91** [comment]
@vjcitn @ogevaert this issue has already been addressed. Thank you
